### ISSUE TITLE
STAPI Fails at reading ressource

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/helgoland-toolbox#123]
https://github.com/52North/helgoland-toolbox/blob/v1.0.0-beta.21/projects/helgoland/core/src/lib/api-communication/connectors/sta-api-v1-connector/read/sta-read-interface.service.ts
Line 203

Fails
STA-Read: sta-tamis/Datastreams(PAAB1GA__-3F04)?$expand=Thing,Thing/Locations,ObservedProperty,Sensor

Works -> ID is in ''
STA-Read: sta-tamis/Datastreams('PAAB1GA__-3F04')?$expand=Thing,Thing/Locations,ObservedProperty,Sensor

**Comment by janschulte** [comment]
Now the STA API didn't need the `'` for the IDs anymore.
