### ISSUE TITLE
Alpha - Angular Eventing Interface Service 

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/helgoland-toolbox#15]
considering current development status of eventing-rest-api
Necessary Implementations for Alpha are these two endpoints with http request attributes
- GetEvents
- GetSubscriptions

**Comment by janschulte** [comment]
Add a new module ``@hegloand/eventing`` with a service ``EventingApiService``

See [here](https://github.com/52North/helgoland-toolbox/blob/feature/ng-v6/src/app/pages/eventing/eventing.component.ts) how to use the EventingApiInterface
