### ISSUE TITLE
[Graph Component] Empty Graph when no observation is in focus

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/helgoland-toolbox#19]
- Extension of Dataset API necessary returning previous and next observation when a requested time interval does not contain an observation
- In this case concerning the rendering hint: When line graph -> draw a line; when point graph -> do nothing
- add two buttons in graph -> jump to previous / jump to next

**Comment by VKirstein** [comment]
Buttons in graph should be added to the legend entries later on.
