### ISSUE TITLE
Requirement List for Visualization of last Measurements on Map

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/helgoland-toolbox#23]

**Comment by simonjirka** [comment]
WV will provide initial version.

**Comment by ChrisMalewski** [comment]
Für den nächsten Meilenstein soll Folgendes umgesetzt werden:
Kartenkomponente:
- AngularInput: lastValuesSeriesIds der Kartenkomponente
- AngularInput: lastValuesPhenomenonId der Kartenkomponente 
- Nur für Punkt Phänomene
- LastValue ist immer der zuletzt gemessene Wert, egal wie alt.
  - Auf der Karte angezeigt werden sollen der letzte Messwert und die Einheit
  - Zeiträume für textuelle Altersangabe (vor 2 Stunden, älter als..) müssen konfigurierbar sein (Beispiel GitHub Notifications)
- Kartenicon ist interaktiv, 
- bei Klick AngularOutput der TimeSeriesId, die Elternkomponente entscheidet dann, was passiert, z.B. Modal mit detaillierter Anzeige des letzten Wertes und Ganglinie im Zeitraum X dadrunter, Link zum Öffnen dieser Timeseries in der Diagrammansicht, 

- bei Hover anderes Styling des Mapicons aktivieren, mehr Details (genaues Datum, Uhrzeit etc) anzeigen
![grafik](https://user-images.githubusercontent.com/871131/45426705-43e4f800-b69d-11e8-8751-9af77cac5853.png)
