### ISSUE TITLE
[Graph Component] Labeling and Skaling of X and Y Axis

### ISSUE THREAD

**Issue by simonjirka** [52North/helgoland-toolbox#52]
- Make labeling more flexible
  - Date formats (languages)
  - Temporal resolution
- Switch to set the scaling of the y axis based on min/max values
- Ensure that the grouping of y axis can be enabled/disabled for individual time series
- Improve readability of labels (when selected)
- Highlighting of axes when time series are selected
- Highlighting of time series by dedicated button and not automatically if legend entry is selected

**Comment by VKirstein** [comment]
Label of y axis when grouping is disabled should be the **uom, Station and phenomenon**. Currently the requested adress of the timeseries is labeled.

**Comment by VKirstein** [comment]
Shown value labels have an offset of one data point. The depicted label has the value of the data point left to the Hovering line. See attached Picture.
![offsetlabel](https://user-images.githubusercontent.com/37791022/46537388-b6ae5100-c8a0-11e8-8644-0e5326ca59a2.png)

**Comment by VKirstein** [comment]
If data Points lie on top of each other the value Labels should be ordered in a better way. Maybe one Label on the right and the other on the left of the hovering line. At least have some space between the single Labels. 
![labelsnexttoeachother](https://user-images.githubusercontent.com/37791022/46538051-718b1e80-c8a2-11e8-9873-8291b8dc0fe4.png)

**Comment by VKirstein** [comment]
When grouping of the yAxis is disabled the graph and the yAxes disappear when setting a dataset not visible.
![groupvisibility](https://user-images.githubusercontent.com/37791022/46538917-b9ab4080-c8a4-11e8-92f4-4de6e73819ff.JPG)
![groupnovisibility](https://user-images.githubusercontent.com/37791022/46538921-be6ff480-c8a4-11e8-9a31-db3595b605d8.JPG)

**Comment by VKirstein** [comment]
Successfully tested. Close Issue.
