### ISSUE TITLE
[Legend] Simplify legend entries

### ISSUE THREAD

**Issue by simonjirka** [52North/helgoland-toolbox#56]

**Comment by janschulte** [comment]
Add new entry hierarchy (see class description for more information):
- https://52north.github.io/helgoland-toolbox/classes/ListEntryComponent.html#info
- https://52north.github.io/helgoland-toolbox/components/SimpleTimeseriesEntryComponent.html
- https://52north.github.io/helgoland-toolbox/components/ConfigurableTimeseriesEntryComponent.html
- https://52north.github.io/helgoland-toolbox/components/FirstLatestTimeseriesEntryComponent.html
