### ISSUE TITLE
Extended service for connecting to the Eventing REST-API

### ISSUE THREAD

**Issue by simonjirka** [52North/helgoland-toolbox#57]
- Support current versions of Events and Subscriptions
- Support of the Publications and Notification endpoints

**Comment by janschulte** [comment]
Add additional endpoint: 
- https://github.com/52North/helgoland-toolbox/blob/develop/projects/helgoland/eventing/src/lib/eventing-api.service.ts
- https://github.com/52North/helgoland-toolbox/blob/develop/projects/helgoland/eventing/src/lib/eventing-impl-api-interface.service.ts

**Comment by ChrisMalewski** [comment]
TESTED and can be CLOSED
